DROP TABLE IF EXISTS formation;
DROP TABLE IF EXISTS etudiant;

CREATE TABLE formation (
  ID INT PRIMARY KEY,
  LIBELLE VARCHAR(250) NOT NULL,
  CHEMIN VARCHAR(250) NOT NULL
);

CREATE TABLE etudiant (
   NUMERO INT PRIMARY KEY,
   NOM VARCHAR(250) NOT NULL,
   PRENOM VARCHAR(250) NOT NULL,
   MAIL VARCHAR(250) NOT NULL,
   FORMATION_ID INT NOT NULL,
   FOREIGN KEY (FORMATION_ID) REFERENCES formation(ID)
);

INSERT INTO formation (ID, LIBELLE, CHEMIN) VALUES
  (1, 'M1 INFO Groupe 1', 'M1/INFO/1'),
  (2, 'M1 INFO Groupe 2', 'M1/INFO/2');

INSERT INTO etudiant (NUMERO, NOM, PRENOM, MAIL, FORMATION_ID) VALUES
 (513145161, 'RAFFORT', 'Adrien', 'adrien73400@icloud.com', 2);
